server:
  port: 8082

spring:
  application:
    name: payment-service
  profiles:
    active: h2

  datasource:
    url: jdbc:h2:mem:payments_db;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  cloud:
    stream:
      binders:
        solace-binder:
          type: solace
          environment:
            solace:
              java:
                host: "tcp://localhost:55555"
                msgVpn: default
                clientUsername: default
                clientPassword: ""
      bindings:
        paymentInitiatedPublisher-out-0:
          destination: banking/v1/payment/initiated
          binder: solace-binder
          content-type: application/json
        handlePaymentCompleted-in-0:
          destination: banking/v1/payment/completed
          group: payment-service-group
          binder: solace-binder
          content-type: application/json
        handlePaymentFailed-in-0:
          destination: banking/v1/payment/failed
          group: payment-service-group
          binder: solace-binder
          content-type: application/json
      function:
        definition: handlePaymentCompleted;handlePaymentFailed

logging:
  level:
    com.banking.payment: DEBUG
